### ISSUE TITLE
Start tag has wrong closing tag - (About.jsp)

### ISSUE THREAD

**Issue by PierreOF** [ArthurSampaio13/jsp-servlet-baseapp#14]
O erro Start tag has wrong closing tag. também é comum para vocês ? 

trecho do código
```
				<tr>
					<td scope="col">Ewerton Mendonça</th>
					<td scope="col">Users</th>
					<td scope="col">Autenticação</th>
				</tr>
				<tr>
					<td scope="col">Jeová Bezerra Leite</th>
					<td scope="col">Arthur Lopes Filgueira Sampaio</th>
					<td scope="col">Marcos Pierre de Melo Monteiro</th>
					<td scope="col">Coloque aqui sua entidade de trabalho</th>
					<td scope="col">Coloque aqui sua regra de negócio</th>
				</tr>
```

**Comment by Jeova-1704** [comment]
acho que não é para ser feito assim

**Comment by Jeova-1704** [comment]
A forma correta é assim:
				<tr>
					<td scope="col">Ewerton Mendonça</th>
					<td scope="col">Users</th>
					<td scope="col">Autenticação</th>
				</tr>
				<tr>
					<td scope="col">Jeová Bezerra Leite</th>
					<td scope="col">Coloque aqui sua entidade de trabalho</th>
					<td scope="col">Coloque aqui sua regra de negócio</th>
				</tr>
				<tr>
					<td scope="col">Arthur Lopes Filgueira Sampaio</th>
					<td scope="col">Coloque aqui sua entidade de trabalho</th>
					<td scope="col">Coloque aqui sua regra de negócio</th>
				</tr>
				<tr>
					<td scope="col">Marcos Pierre de Melo Monteiro</th>
					<td scope="col">Coloque aqui sua entidade de trabalho</th>
					<td scope="col">Coloque aqui sua regra de negócio</th>
				</tr>

**Comment by PierreOF** [comment]
pode iniciar a refatoração?

**Comment by Jeova-1704** [comment]
@ArthurSampaio13 valide na sua por favor

**Comment by ArthurSampaio13** [comment]
Vou corrigir a minha após a de Pierre

**Comment by ArthurSampaio13** [comment]
@PierreOF já terminou de alterar essa parte?

**Comment by PierreOF** [comment]
> @PierreOF já terminou de alterar essa parte?

estou finalizando

**Comment by ArthurSampaio13** [comment]
Conseguiu finalizar?

**Comment by ArthurSampaio13** [comment]
@PierreOF

**Comment by Jeova-1704** [comment]
@PierreOF

**Comment by PierreOF** [comment]
> @PierreOF

já subi com minha alteração

**Comment by ArthurSampaio13** [comment]
Finalizou?

**Comment by ArthurSampaio13** [comment]
@PierreOF Finalizou tudo?

**Comment by Jeova-1704** [comment]
que problema em uma nova tag? @PierreOF

**Comment by PierreOF** [comment]
> que problema em uma nova tag? @PierreOF

aqui o intelij está reclamando do erro , "Start tag has wrong closing tag"

**Comment by ArthurSampaio13** [comment]
Posso dar o merge final?

**Comment by Jeova-1704** [comment]
@PierreOF se estiver igual ao meu não dá erro, pode ver, copia e cola do meu e manda

**Comment by PierreOF** [comment]
@ArthurSampaio13 espera um pouco

**Comment by Jeova-1704** [comment]
vou abrir no meu para ver se dá esse erro @PierreOF

**Comment by PierreOF** [comment]
> @PierreOF se estiver igual ao meu não dá erro, pode ver, copia e cola do meu e manda

estou atualizado com a dev

**Comment by Jeova-1704** [comment]
@PierreOF Acabei de olhar e não é erro não, é apenas que está obsoleto mas pode mandar

**Comment by PierreOF** [comment]
> @PierreOF Acabei de olhar e não é erro não, é apenas que está obsoleto mas pode mandar

o que está obsoleto é o uso do scope="col": 
log: 
Remove this deprecated "scope" attribute.

**Comment by Jeova-1704** [comment]
mas está funcionando, todo mundo está desse jeito

**Comment by Jeova-1704** [comment]
manda bala @ArthurSampaio13

**Comment by Jeova-1704** [comment]
@PierreOF corrigiu?

**Comment by PierreOF** [comment]
> @PierreOF corrigiu?

não foi passada a task de corrigir , acredito que o arquivo já estava com esse erro

**Comment by PierreOF** [comment]
substituor o td por th parece funcionar.

antigo:
<td scope="col">Coloque aqui sua entidade de trabalho</th>

correção: 
<th scope="col">Coloque aqui sua entidade de trabalho</th>

**Comment by PierreOF** [comment]
ok
