### ISSUE TITLE
github actions

### ISSUE THREAD

**Issue by Jeova-1704** [ArthurSampaio13/jsp-servlet-baseapp#17]
As actions não foram ativadas quando o código subiu na developer, é bom validar isso @PierreOF @ArthurSampaio13

**Comment by ArthurSampaio13** [comment]
Boa pergunta, não sei o motivo

**Comment by Jeova-1704** [comment]
vou olhar isso

**Comment by Jeova-1704** [comment]
olha ai tb

**Comment by Jeova-1704** [comment]
@ArthurSampaio13 tu que é o dono do repositório olha para mim por favor

**Comment by ArthurSampaio13** [comment]
Pessoal! Deu erro no processo do github actions

**Comment by ArthurSampaio13** [comment]
@Jeova-1704 @PierreOF

**Comment by Jeova-1704** [comment]
nada do github actions lá está funcionando, temos que ver
eu consegui colocar para rodar, mas ele está dando erro quando está rodando

**Comment by Jeova-1704** [comment]
eu consegui corrigir

**Comment by Jeova-1704** [comment]
vou subir na development para ver

**Comment by ArthurSampaio13** [comment]
Correção feita, pessoal! @Jeova-1704 @PierreOF. Fiz esse último commit UPDATE README.MD só para disparar o job
